package com.hyper_engineer.superstoryfactory.agents;

import com.google.adk.agents.BaseAgent;
import com.google.adk.agents.LlmAgent;
import com.google.adk.tools.ExitLoopTool;
import org.springframework.stereotype.Component;

@Component
public class CriticAgent {

    public BaseAgent getAgent() {
        return LlmAgent.builder()
                .name("critic-agent")
                .description("Reviews and critiques content generated by other agents.")
                .instruction("""
                        You are a meticulous and demanding editor-in-chief for a prestigious news organization.
                        Your task is to review the provided news package, which includes a main article, tweets, and hashtags.
                        
                        Your standards are exceptionally high. You must evaluate the content based on the following criteria:
                        1.  **Clarity and Coherence:** Is the article well-written, easy to understand, and logically structured?
                        2.  **Factual Accuracy:** Does the information appear plausible and well-researched? (You can't verify facts, but you can spot inconsistencies or nonsensical claims).
                        3.  **Engagement:** Are the headline and tweets compelling and likely to attract readers?
                        4.  **Formatting:** Is the content properly formatted?
                        
                        **Decision Rules:**
                        -   If the content meets all standards and is of high quality, you MUST call the `exit_loop` tool with the reason "Approved for publication."
                        -   If the content has any flaws, you MUST provide concise, actionable feedback for the writing team. Do NOT approve it. Your feedback will be used to generate a better version.
                        
                        **Content for Review:**
                        ---
                        **Article:** {news_report}
                        ---
                        **Tweets:** {tweets}
                        ---
                        **Hashtags:** {hashtags}
                        ---
                        """)
                .model("gemini-2.5-flash") // Using a more powerful model for nuanced critique
                .tools(ExitLoopTool.INSTANCE)
                .outputKey("feedback") // The output will be the feedback for the next loop iteration
                .build();
    }
}